### ISSUE TITLE
Use Renovate

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-actions-template#8]
Related: #2

**Comment by ianlewis** [comment]
Renovate allows for easier grouping of updates etc. but since this is a template for end-users, maybe we should just leave it using dependabot since that's kind of the default on GitHub?

@laurentsimon @asraa wdut?

**Comment by laurentsimon** [comment]
I don't have a strong opinion, so long as we're able to tell downstream users how to configure these tools to pin the workflows by `version` and ensure the tools don't accidentally try to update it to hash pins.

**Comment by ianlewis** [comment]
Right. you basically mean [RENOVATE.md](https://github.com/slsa-framework/slsa-github-generator/blob/63be127d844243f1458166190bbcefd56a1e1de0/RENOVATE.md).

I'm not sure how to ensure that references are pinned by digest except for slsa-github-generator workflows so maybe switching to Renovate would be best.

As an aside, We don't seem to even have the config in RENOVATE.md in our own renovate config. Do you remember what prevents Renovate from upgrading our references to our own actions? (for example [here](https://github.com/slsa-framework/slsa-github-generator/blob/63be127d844243f1458166190bbcefd56a1e1de0/.github/workflows/builder_go_slsa3.yml#L90)). I guess it's just because we haven't set `pinGitHubActionDigests` ourselves?

**Comment by laurentsimon** [comment]
I'm not sure either. Probably the option you're referring to is the reason. 
I also recall filing a bug a while ago that `@main` should not be updated by default to a hash, and maybe they have changed the behavior since then
